[project]
name = "vsc-base"
version = "4.0.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Andy Georges", email = "itkovian@gmail.com" }
]
requires-python = ">=3.9,<4.0"
dependencies = []
packages = [
    {include = "vsc", from="src"}
]

[build-system]
requires = ["uv_build>=0.8.18,<0.9.0"]
build-backend = "uv_build"

[project.scripts]
